[phases.setup]
nixPkgs = [
  "python312",
  "cairo",
  "pango",
  "gdk-pixbuf",
  "libffi",
  "gobject-introspection",
  "shared-mime-info",
  "fontconfig",
]
nixLibs = [
  "glib",
  "cairo",
  "pango",
  "gdk-pixbuf",
  "fontconfig",
  "libffi",
  "freetype",
  "harfbuzz",
]
